languageCode = 'en-us'
title = 'wenrir'
theme = "hugo-bearcub"
baseURL = 'https://wenrir.github.io/'
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
paginate = 10
rssLimit = 10
summarylength = 20 
defaultContentLanguage = "en"

copyright = ""

[build.buildStats]
  enable = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true
