title = 'wenrir'

showLineNumbers = true
uniqueHomePage = false
#
enableCopyright = false

mainSections = ["posts", "notes"]
[doks]
  sectionNav = ["config", "posts", "notes", "exercises"]
  breadcrumbTrail = true 
  colorMode = "dark"
  colorModeToggler = false
  navbarSticky = true
  showDate = true 
  searchLimit = 10 # 0 (no limit, default) or natural number
  repoHost = "GitHub" # GitHub (default), Gitea, GitLab, Bitbucket, or BitbucketServer
  docsRepo = "https://github.com/wenrir/wenrir.github.io"
  docsRepoBranch = "main" # main (default), master, or <branch name>

