dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
homeSubtitle = "www"
disableReadOtherPosts = false
enableSharingButtons = true
enableGlobalLanguageMenu = false
description = "Mainly collection of notes that other might but most likely wont find useful."
keywords = "homepage, blog"
images = [""]