[[main]]
  name = "Posts"
  identifier = "posts"
  weight = 5
  url = "/posts"

[[main]]
  name = "Config"
  identifier = "config"
  weight = 2
  url = "/config"

[[main]]
  name = "Notes"
  identifier = "notes"
  weight = 2
  url = "/notes"

[[main]]
  name = "Exercises"
  identifier = "exercises"
  weight = 2
  url = "/exercises"