languageCode = 'en-us'
title = 'Wenrir'
theme = "compose"
baseURL = 'https://wenrir.github.io/'
enableCopyright = false
uniqueHomePage = true

[params]
  subtitle = 'It is the truth which conceals that there is none...'
[outputs]
  home = ["HTML", "RSS","JSON"]
