languageCode = 'en-us'
title = 'Welcome!'
theme = "archie"
baseURL = 'https://wenrir.github.io/'
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
paginate = 10
rssLimit = 10
summarylength = 20 
defaultContentLanguage = "en"
pygmentsStyle          = "gruvbox"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true


copyright = ""

[build.buildStats]
  enable = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "wenrir"
