languageCode = 'en-us'
title = 'W'
theme = "archie"
baseURL = 'https://wenrir.github.io/'
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
paginate = 3
rssLimit = 10
summarylength = 20 
defaultContentLanguage = "en"
pygmentsStyle          = "gruvbox"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

copyright = "© There's no copyright on the internet."

[build.buildStats]
  enable = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true

[params.author]
  name = "wenrir"

[params]
mode="dark" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Mainly collection of notes that other might but most likely wont find useful. Please be careful when using or refering to any information on these pages, as it's not intended to be used for any other reason than my own learning."
mathjax = true # enable MathJax support
katex = true # enable KaTeX support
[[params.social]]
  name = "github"
  url  = "https://github.com/wenrir/"

[[menu.main]]
  name = "Posts"
  identifier = "posts"
  weight = 5
  url = "/content/posts"

[[menu.main]]
  name = "Config"
  identifier = "config"
  weight = 2
  url = "/content/config"

[[menu.main]]
  name = "Notes"
  identifier = "notes"
  weight = 2
  url = "/content/notes"

[[menu.main]]
  name = "Exercises"
  identifier = "exercises"
  weight = 2
  url = "/content/exercises"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
