[[main]]
  name = "posts"
  weight = 5
  url = "/posts/"

[[main]]
  name = "configs"
  weight = 2
  url = "/config/"

[[main]]
  name = "notes"
  weight = 2
  url = "/notes/"

[[main]]
  name = "exercises"
  weight = 2
  url = "/exercises/"